name: Java CI with Gradle

on:
  push:
    branches-ignore:
      - main
      - develop
      - 'fe/**'

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'testDB'
          mysql user: 'test'
          mysql password: 'test'

      - name: Create application.yml
        run: |
          mkdir -p ./backend/src/main/resources
          cat <<EOT > ./backend/src/main/resources/application.yml
          spring:
            datasource:
              url: jdbc:mysql://localhost:3306/testDB
              username: test
              password: test
              driver-class-name: com.mysql.cj.jdbc.Driver

            jpa:
              hibernate:
                ddl-auto: create
              show-sql: true
              properties:
                hibernate:
                  format_sql: true

            data:
              redis:
                host: localhost
                port: 6379

          logging:
            level:
              web: debug

          commit:
            hash: test

          cloud:
              aws:
                  credentials:
                      access-key: dummy-key-for-test
                      secret-key: dummy-secret-for-test
                  region: ap-northeast-2
                  s3:
                      bucket: dummy-bucket-for-test

          EOT
        shell: bash

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Get short SHA
        id: slug
        run: echo "sha7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test
        working-directory: ./backend
